require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Minimum iOS version 12.0 as per requirements
platform :ios, '12.0'
install! 'cocoapods', :deterministic_uuids => false

target 'VendorApp' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default for better performance
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # React Native Camera for freshness scanning
  # Using react-native-vision-camera instead of deprecated react-native-camera
  
  # React Native Voice for audio recording
  # Using @react-native-voice/voice
  
  # Geolocation for distance calculation
  # Using @react-native-community/geolocation
  
  # Vector Icons
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  
  target 'VendorAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    
    # Fix for Xcode 14+ deployment target warnings
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
